import "./WebCLGL.class";
module.exports.WebCLGL = global.WebCLGL = WebCLGL;
import "./WebCLGLBuffer.class";
module.exports.WebCLGLBuffer = global.WebCLGLBuffer = WebCLGLBuffer;
import "./WebCLGLFor.class";
module.exports.WebCLGLFor = global.WebCLGLFor = WebCLGLFor;
import "./WebCLGLKernel.class";
module.exports.WebCLGLKernel = global.WebCLGLKernel = WebCLGLKernel;
import "./WebCLGLUtils.class";
module.exports.WebCLGLUtils = global.WebCLGLUtils = WebCLGLUtils;
import "./WebCLGLVertexFragmentProgram.class";
module.exports.WebCLGLVertexFragmentProgram = global.WebCLGLVertexFragmentProgram = WebCLGLVertexFragmentProgram;